[package]
name = "pixeltask"
version = "0.1.0"
authors = ["Shawn Lim <shawn.lim@local>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.22.4"
clap = "2.33.0"